// <auto-generated />
namespace HealthBlog.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class sil3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sil3));
        
        string IMigrationMetadata.Id
        {
            get { return "202109181544368_sil3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
