// <auto-generated />
namespace HealthBlog.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addaboutcreateddate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addaboutcreateddate));
        
        string IMigrationMetadata.Id
        {
            get { return "202109061408266_addaboutcreateddate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
