// <auto-generated />
namespace HealthBlog.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addabout3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addabout3));
        
        string IMigrationMetadata.Id
        {
            get { return "202109061332075_addabout3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
